version: 2.1


jobs:
    test:
      docker:
        - image: circleci/node:14.4-browsers
      steps:
        - checkout
        - run:
            name: install packages
            command: npm install
        - run:
            name: Running unit test
            command: npm test -- --browsers ChromeHeadless --watch=false


workflows:
    angular-test:
        jobs:
         - test
            