version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.16

jobs:
    test:
      docker:
        - image: circleci/node:14.4-browsers
      steps:
        - checkout
        - run:
            name: Install angular-cli
            command: npm install @angular/cli 
        - run:
            name: Install packages
            command: npm install
        - run:
            name: Running unit test
            command: node_modules/@angular/cli/bin/ng test -- --browsers ChromeHeadless --watch=false
        - run:
            name: Building project
            command: node_modules/@angular/cli/bin/ng build --prod 
        - persist_to_workspace:
            root: ./dist
            paths:
              - vuelos-front
    build:
      docker:
        - image: 'cimg/python:3.6'
      steps:
        - attach_workspace:
            at: ./
        - aws-s3/sync:
            from: vuelos-front
            overwrite: true
            to: 's3://vuelos-front/'

workflows:
    angular-test:
        jobs:
          - test
          - build:
              context: AWSCONTEXT
              requires:
                - test
              filters:
                branches:
                  only: master
          
        
            