version: 2.1


jobs:
    test:
      docker:
        - image: circleci/node:14.4-browsers
      steps:
        - checkout
        - run:
            name: Install angular-cli
            command: npm install @angular/cli 
        - run:
            name: Install packages
            command: npm install
        - run:
            name: Running unit test
            command: node_modules/@angular/cli/bin/ng test -- --browsers ChromeHeadless --watch=false


workflows:
    angular-test:
        jobs:
         - test
            